export { GamesDataFile, PlayersDataFile };

const GamesDataFile =
{
  "success": true,
  "data": {
    "games": [
      {
        "local": true,
        "opponent": "Deportivo Saprissa",
        "opponent_image": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Saprissa_New_Logo.png",
        "datetime": "2019-07-12T01:00:00+00:00",
        "league": "Amistoso",
        "image": "https://venados.dacodes.mx/img/usr/99f8469c13f74a8caa8860dfcc9f844d.jpg",
        "home_score": 2,
        "away_score": 2
      },
      {
        "local": true,
        "opponent": "Atlante",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/2/2.png",
        "datetime": "2019-07-31T00:00:00+00:00",
        "league": "Copa MX",
        "image": "https://venados.dacodes.mx/img/usr/c1a148f279de4878a718f634b6aa2e44.jpg",
        "home_score": 4,
        "away_score": 1
      },
      {
        "local": false,
        "opponent": "Loros",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/145/145.png",
        "datetime": "2019-08-03T22:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/40a243c79b61442086daef1de7f7f38b.jpg",
        "home_score": 1,
        "away_score": 2
      },
      {
        "local": false,
        "opponent": "FC Juárez",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10725/10725.png",
        "datetime": "2019-08-07T02:00:00+00:00",
        "league": "Copa MX",
        "image": "https://venados.dacodes.mx/img/usr/7a6c0eac94d74c6f9e769f35141628c1.jpg",
        "home_score": 1,
        "away_score": 1
      },
      {
        "local": true,
        "opponent": "U. A. Edo. Méx.",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/171/171.png",
        "datetime": "2019-08-11T00:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/13fbd85b8b874f1195d82da90bfbb494.jpg",
        "home_score": 1,
        "away_score": 1
      },
      {
        "local": true,
        "opponent": "U. de G.",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/33/33.png",
        "datetime": "2019-08-17T00:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/3abec1d5f5b84688910a4537517f51ee.jpg",
        "home_score": 1,
        "away_score": 0
      },
      {
        "local": false,
        "opponent": "Dorados",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/3111/3111.png",
        "datetime": "2019-08-25T02:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/9aaeba76f8ee4ae78d88b59d5e8fa83c.jpg",
        "home_score": 1,
        "away_score": 0
      },
      {
        "local": true,
        "opponent": "Mineros",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10449/10449.png",
        "datetime": "2019-08-31T02:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/c4691566ae3145999b1b90c0b6dc32cd.jpg",
        "home_score": 1,
        "away_score": 2
      },
      {
        "local": true,
        "opponent": "FC Juárez",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10725/10725.png",
        "datetime": "2019-09-05T00:00:00+00:00",
        "league": "Copa MX",
        "image": "https://venados.dacodes.mx/img/usr/e0bdfd5dc5cf4ce486ea542cdb7b7d87.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": false,
        "opponent": "Cimarrones",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10721/10721.png",
        "datetime": "2019-09-15T03:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/b5c002d1a24843f3bbd22b76970fde65.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": true,
        "opponent": "Alebrijes",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/3088/3088.png",
        "datetime": "2019-09-21T03:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/258a704317ae4e43ba36cecf78c9b969.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": false,
        "opponent": "Celaya F.C.",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10726/10726.png",
        "datetime": "2019-09-29T17:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/918dc5f24491404cacf3f6dc57dd148c.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": false,
        "opponent": "Club Atlético Zacatepec ",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/11221/11221.png",
        "datetime": "2019-10-04T01:30:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/e095017f3e0149aab4ed85ace7dbcfee.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": true,
        "opponent": "TM Fútbol Club",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos/10962/10962.png",
        "datetime": "2019-10-19T02:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/e2fd2d5e618a47acb8ed41bef7fbddd7.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": false,
        "opponent": "Cafetaleros",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos/11779/11779.png",
        "datetime": "2019-10-27T01:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/16a997d826604339a1211646c0c3cefd.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": true,
        "opponent": "Atlante",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/2/2.png",
        "datetime": "2019-11-02T02:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/5166905f90be465d90dd1d0c9cd2da65.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": false,
        "opponent": "Atlante",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/2/2.png",
        "datetime": "2019-11-06T01:00:00+00:00",
        "league": "Copa MX",
        "image": "https://venados.dacodes.mx/img/usr/b855fead6f2a4d03b1bfb358cd10fc3f.jpg",
        "home_score": 0,
        "away_score": 0
      },
      {
        "local": false,
        "opponent": "Correcaminos",
        "opponent_image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/21/21.png",
        "datetime": "2019-11-09T02:00:00+00:00",
        "league": "Ascenso MX",
        "image": "https://venados.dacodes.mx/img/usr/d92ea74c63b84c65802588994ef801b8.jpg",
        "home_score": 0,
        "away_score": 0
      }
    ],
    "code": 200
  }
}

const PlayersDataFile = 
{
  "success": true,
  "data": {
      "team": {
          "forwards": [
              {
                  "name": "Esteban",
                  "first_surname": "Torres",
                  "second_surname": "Rivera",
                  "birthday": "1999-06-27T00:00:00+00:00",
                  "birth_place": "Ciudad Madero, Tamaulipas",
                  "weight": 65,
                  "height": 1.82,
                  "position": "Delantero",
                  "number": 15,
                  "position_short": "DEL",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/6c0f2264ef654a3ca139c982a842144f.jpg"
              },
              {
                  "name": "Alan",
                  "first_surname": "Guillermo",
                  "second_surname": "Murialdo",
                  "birthday": "1992-09-24T00:00:00+00:00",
                  "birth_place": "Argentina",
                  "weight": 85,
                  "height": 1.93,
                  "position": "Delantero",
                  "number": 20,
                  "position_short": "DEL",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/64ad407f61b24435bd36c77051bb0c4f.jpg"
              },
              {
                  "name": "Abraham Darío",
                  "first_surname": "Carreño",
                  "second_surname": "Rohan",
                  "birthday": "1988-01-13T00:00:00+00:00",
                  "birth_place": "Monterrey, Nuevo León",
                  "weight": 81,
                  "height": 1.83,
                  "position": "Delantero",
                  "number": 9,
                  "position_short": "DEL",
                  "last_team": "Puebla F.C.",
                  "image": "https://venados.dacodes.mx/img/usr/571cf02d1a194a9e8e190558bbeaa1a0.jpg"
              },
              {
                  "name": "Carlos Gael",
                  "first_surname": "Acosta",
                  "second_surname": "Zavala",
                  "birthday": "1992-03-26T00:00:00+00:00",
                  "birth_place": "Ahome, Sinaloa,",
                  "weight": 64,
                  "height": 1.65,
                  "position": "Delantero",
                  "number": 19,
                  "position_short": "DEL",
                  "last_team": "Gallos Blancos de Queretaro.",
                  "image": "https://venados.dacodes.mx/img/usr/c0274beda3be43a1aed702692cb860e6.jpg"
              },
              {
                  "name": "Mathews",
                  "first_surname": "Gomes",
                  "second_surname": "Da Silva",
                  "birthday": "1996-04-09T00:00:00+00:00",
                  "birth_place": "Santiago de Querétaro, Querétaro",
                  "weight": 72,
                  "height": 1.79,
                  "position": "Delantero",
                  "number": 22,
                  "position_short": "DEL",
                  "last_team": "Yalmakan FC",
                  "image": "https://venados.dacodes.mx/img/usr/5dcad9b75e0740afa869d463dc6011e4.jpg"
              }
          ],
          "centers": [
              {
                  "name": "Eduardo",
                  "first_surname": "Fernández",
                  "second_surname": "Aldana",
                  "birthday": "1990-04-03T00:00:00+00:00",
                  "birth_place": "Mérida, Yucatán",
                  "weight": 70,
                  "height": 1.74,
                  "position": "Mediocampista",
                  "number": 7,
                  "position_short": "MED",
                  "last_team": "Venados F.C.",
                  "image": "https://venados.dacodes.mx/img/usr/87dd90bcc04047a785b29ee390999544.jpg"
              },
              {
                  "name": "Manuel Alejandro",
                  "first_surname": "Vela",
                  "second_surname": "Garrido",
                  "birthday": "1984-03-28T00:00:00+00:00",
                  "birth_place": "Cancún, Quintana Roo",
                  "weight": 72,
                  "height": 1.72,
                  "position": "Mediocampista",
                  "number": 11,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/8ede6e137f0041d08e91b19ae78b20d9.jpg"
              },
              {
                  "name": "Aldo Francisco",
                  "first_surname": "Polo",
                  "second_surname": "Ramírez",
                  "birthday": "1983-10-31T00:00:00+00:00",
                  "birth_place": "Ciudad de México",
                  "weight": 72,
                  "height": 1.75,
                  "position": "Mediocampista",
                  "number": 8,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/0ce11d263ebd40a7b8a17d93c0b134ea.jpg"
              },
              {
                  "name": "Víctor Manuel",
                  "first_surname": "Zúñiga",
                  "second_surname": "Medina",
                  "birthday": "1996-03-21T00:00:00+00:00",
                  "birth_place": "Nezahualycóyotl, Estado de México",
                  "weight": 63,
                  "height": 1.75,
                  "position": "Mediocampista",
                  "number": 16,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/626270de74d24916afae7ebac1e5b4f3.jpg"
              },
              {
                  "name": "Heider Uriel",
                  "first_surname": "Ruiz",
                  "second_surname": "Carrera",
                  "birthday": "1998-07-28T00:00:00+00:00",
                  "birth_place": "Chetumal, Quintana Roo",
                  "weight": 63,
                  "height": 1.72,
                  "position": "Mediocampista",
                  "number": 23,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/a5ea62057578415d9d2903a2d6866e87.jpg"
              },
              {
                  "name": "José David",
                  "first_surname": "Rosado",
                  "second_surname": "Reyes",
                  "birthday": "1999-05-03T00:00:00+00:00",
                  "birth_place": "Mérida, Yucatán",
                  "weight": 56,
                  "height": 1.72,
                  "position": "Mediocampista",
                  "number": 26,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/d2498555526249d3bb710986cd4c5fc5.jpg"
              },
              {
                  "name": "Francisco Paúl",
                  "first_surname": "Uscanga",
                  "second_surname": "Gutiérrez",
                  "birthday": "1991-03-25T00:00:00+00:00",
                  "birth_place": "Coatzacoalcos, Veracruz",
                  "weight": 59,
                  "height": 1.65,
                  "position": "Mediocampista",
                  "number": 27,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/a4f0e618b8b44de5b11d52eccca7ad03.jpg"
              },
              {
                  "name": "Alfonso",
                  "first_surname": "Tamay",
                  "second_surname": "Sánchez",
                  "birthday": "1993-05-13T00:00:00+00:00",
                  "birth_place": "Cancún, Quintana Roo",
                  "weight": 62,
                  "height": 1.65,
                  "position": "Mediocampista",
                  "number": 13,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/3a159406dc224e01bf8db28b59385246.jpg"
              },
              {
                  "name": "Jorge José",
                  "first_surname": "Ibarra",
                  "second_surname": "Sánchez",
                  "birthday": "1988-08-29T00:00:00+00:00",
                  "birth_place": "Guadalajara, Jalisco",
                  "weight": 70,
                  "height": 1.7,
                  "position": "Mediocampista",
                  "number": 29,
                  "position_short": "MED",
                  "last_team": "Lobos BUAP",
                  "image": "https://venados.dacodes.mx/img/usr/475c701a11304f2c84503d6938dbfd67.jpg"
              },
              {
                  "name": "Sergio Javier",
                  "first_surname": "Nápoles",
                  "second_surname": "Saucedo",
                  "birthday": "1989-11-23T00:00:00+00:00",
                  "birth_place": "Cancún, Quintana Roo",
                  "weight": 70,
                  "height": 1.68,
                  "position": "Mediocampista",
                  "number": 18,
                  "position_short": "MED",
                  "last_team": "Alebrijes de Oaxaca",
                  "image": "https://venados.dacodes.mx/img/usr/65c87f504d45440389e4a8dc4a7a6980.jpg"
              },
              {
                  "name": "Luis Alberto",
                  "first_surname": "Sánchez",
                  "second_surname": "Rodríguez",
                  "birthday": "1988-02-06T00:00:00+00:00",
                  "birth_place": "Tijuana, Baja California",
                  "weight": 74,
                  "height": 1.75,
                  "position": "Mediocampista",
                  "number": 21,
                  "position_short": "MED",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/2c62e394e817484695cc64fbf24e679f.jpg"
              },
              {
                  "name": "Víctor",
                  "first_surname": "Peniche",
                  "second_surname": "Saenz",
                  "birthday": "1999-01-15T00:00:00+00:00",
                  "birth_place": "Mérida, Yucatán",
                  "weight": 67,
                  "height": 1.7,
                  "position": "Mediocampista",
                  "number": 24,
                  "position_short": "MED",
                  "last_team": "Cantera Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/b7413ba46c644e3cafc0a16577f78f94.jpg"
              },
              {
                  "name": "Gustavo",
                  "first_surname": "Nuñez",
                  "second_surname": "Villamil",
                  "birthday": "1999-12-03T00:00:00+00:00",
                  "birth_place": "Cuernavaca, Morelos",
                  "weight": 62,
                  "height": 1.76,
                  "position": "Mediocampista",
                  "number": 30,
                  "position_short": "MED",
                  "last_team": "Zacatepec",
                  "image": "https://venados.dacodes.mx/img/usr/e6621caac54949aca8f19ee2a0cee655.jpg"
              }
          ],
          "defenses": [
              {
                  "name": "Jonathan Alejandro",
                  "first_surname": "Sánchez",
                  "second_surname": "Hernández",
                  "birthday": "1994-03-13T00:00:00+00:00",
                  "birth_place": "Ciudad Valles, San Luis Potosí",
                  "weight": 70,
                  "height": 1.72,
                  "position": "Defensa",
                  "number": 4,
                  "position_short": "DEF",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/9cd3fedb27b24ae79e5b9fe1711b27e9.jpg"
              },
              {
                  "name": "Carlos Alberto",
                  "first_surname": "Galeana",
                  "second_surname": "Irra ",
                  "birthday": "1988-12-21T00:00:00+00:00",
                  "birth_place": "Tecpan, Guerrero",
                  "weight": 78,
                  "height": 1.8,
                  "position": "Defensa",
                  "number": 3,
                  "position_short": "DEF",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/75996116cdff40d69e56342f81d68c88.jpg"
              },
              {
                  "name": "Carlos Josafat",
                  "first_surname": "Ramos",
                  "second_surname": "Ibarra",
                  "birthday": "1986-11-12T00:00:00+00:00",
                  "birth_place": "Celaya, Guanajuato",
                  "weight": 82,
                  "height": 1.8,
                  "position": "Defensa",
                  "number": 6,
                  "position_short": "DEF",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/9caeef4f0c0b4c6c9e775b1b5c7e0f1e.jpg"
              },
              {
                  "name": "Richard",
                  "first_surname": "Okunorobo",
                  "second_surname": "Islas",
                  "birthday": "1988-08-14T00:00:00+00:00",
                  "birth_place": "Puebla, Puebla",
                  "weight": 80,
                  "height": 1.9,
                  "position": "Defensa",
                  "number": 2,
                  "position_short": "DEF",
                  "last_team": "Alebrijes de Oaxaca",
                  "image": "https://venados.dacodes.mx/img/usr/34e3f216f49b4701a3e5a433902ad5f3.jpg"
              },
              {
                  "name": "Héctor",
                  "first_surname": "Acosta",
                  "second_surname": "Quintero",
                  "birthday": "1991-11-24T00:00:00+00:00",
                  "birth_place": "San Martín Hidalgo, Jalisco",
                  "weight": 77,
                  "height": 1.78,
                  "position": "Defensa",
                  "number": 5,
                  "position_short": "DEF",
                  "last_team": "Toluca",
                  "image": "https://venados.dacodes.mx/img/usr/247477a8770644479f87e890a207edfd.jpg"
              },
              {
                  "name": "Abraham",
                  "first_surname": "Coronado",
                  "second_surname": "Tafoya",
                  "birthday": "1992-02-28T00:00:00+00:00",
                  "birth_place": "Ocotlán, Jalisco",
                  "weight": 78,
                  "height": 1.79,
                  "position": "Defensa",
                  "number": 14,
                  "position_short": "DEF",
                  "last_team": "Loros de la Univ. de Colima.",
                  "image": "https://venados.dacodes.mx/img/usr/10f2ba2cf30c460883e253b351976b57.jpg"
              },
              {
                  "name": "Alberto Carlos",
                  "first_surname": "Hernández",
                  "second_surname": "Téllez",
                  "birthday": "1999-04-27T00:00:00+00:00",
                  "birth_place": "Poza Rica de Hidalgo, Veracruz",
                  "weight": 74.2,
                  "height": 1.75,
                  "position": "Defensa",
                  "number": 17,
                  "position_short": "DEF",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/da93c4623a61448aaf1a63750d9104f4.jpg"
              },
              {
                  "name": "Gonzalo",
                  "first_surname": "Camargo",
                  "second_surname": "Pintos",
                  "birthday": "1991-02-16T00:00:00+00:00",
                  "birth_place": "Artigas, Uruguay",
                  "weight": 70,
                  "height": 1.73,
                  "position": "Defensa",
                  "number": 33,
                  "position_short": "DEF",
                  "last_team": "Racing Club",
                  "image": "https://venados.dacodes.mx/img/usr/99d67413bf85465ba3fa076c8f552a0d.jpg"
              },
              {
                  "name": "Héctor",
                  "first_surname": "Ortegón",
                  "second_surname": "Villareal",
                  "birthday": "1999-12-21T00:00:00+00:00",
                  "birth_place": "Nuevo León, Monterrey",
                  "weight": 72,
                  "height": 1.76,
                  "position": "Defensa",
                  "number": 31,
                  "position_short": "DEF",
                  "last_team": "Deportiva Venados",
                  "image": "https://venados.dacodes.mx/img/usr/243e6594cd6f4d43b95a284c67c1bc41.jpg"
              },
              {
                  "name": "Adonay",
                  "first_surname": "González",
                  "second_surname": "Baak",
                  "birthday": "1999-07-03T00:00:00+00:00",
                  "birth_place": "Motul, Yucatán",
                  "weight": 61,
                  "height": 1.72,
                  "position": "Defensa",
                  "number": 32,
                  "position_short": "DEF",
                  "last_team": "Cantera Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/08ca01c52e5b4af59da9fe273f86e884.jpg"
              }
          ],
          "goalkeepers": [
              {
                  "name": "Armando",
                  "first_surname": "Navarrete",
                  "second_surname": "García",
                  "birthday": "1980-11-22T00:00:00+00:00",
                  "birth_place": "Jacona, Michoacán",
                  "weight": 80,
                  "height": 1.8,
                  "position": "Portero",
                  "number": 12,
                  "position_short": "POR",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/8729c4bf0cfd491f9e9bc55a08f6d74a.jpg"
              },
              {
                  "name": "Rafael",
                  "first_surname": "Ramírez",
                  "second_surname": "Miranda",
                  "birthday": "1992-11-04T00:00:00+00:00",
                  "birth_place": "Guadalajara, Jalisco",
                  "weight": 75,
                  "height": 1.8,
                  "position": "Portero",
                  "number": 28,
                  "position_short": "POR",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/3a83e5fa44114a5d8cf44dcbe6b3b2ee.jpg"
              },
              {
                  "name": "Raiko",
                  "first_surname": "Arozarena",
                  "second_surname": "González",
                  "birthday": "1997-03-27T00:00:00+00:00",
                  "birth_place": "Pinar del Río, Cuba",
                  "weight": 82,
                  "height": 1.83,
                  "position": "Portero",
                  "number": 1,
                  "position_short": "POR",
                  "last_team": "Venados FC",
                  "image": "https://venados.dacodes.mx/img/usr/0c3313a1cbec4112ac376c518a3f9000.jpg"
              }
          ],
          "coaches": [
              {
                  "name": "Sergio",
                  "first_surname": "Orduña",
                  "second_surname": "Carrillo",
                  "birthday": "1954-04-04T00:00:00+00:00",
                  "birth_place": "Morelos",
                  "weight": null,
                  "height": null,
                  "role": "Director Técnico",
                  "role_short": "DT",
                  "image": "https://venados.dacodes.mx/img/usr/ae3a1f5d06bb43f7bd5f4673d96ef273.jpg"
              },
              {
                  "name": "Jesús Salvador",
                  "first_surname": "Aguado",
                  "second_surname": "Olvera",
                  "birthday": "1971-12-16T00:00:00+00:00",
                  "birth_place": "Querétaro",
                  "weight": null,
                  "height": null,
                  "role": "Auxiliar",
                  "role_short": "Aux",
                  "image": "https://venados.dacodes.mx/img/usr/670a36692aa24007bffa5cad8eaf5caf.jpg"
              },
              {
                  "name": "Valtencir",
                  "first_surname": "Gomes",
                  "second_surname": "Da Silva",
                  "birthday": "1969-12-26T00:00:00+00:00",
                  "birth_place": "Sao Paulo",
                  "weight": null,
                  "height": null,
                  "role": "Auxiliar",
                  "role_short": "Aux",
                  "image": "https://venados.dacodes.mx/img/usr/6456404db776437bb6a7ba5811ee54ab.jpg"
              },
              {
                  "name": "Olimpo",
                  "first_surname": "Campos",
                  "second_surname": "Pineda",
                  "birthday": "1968-10-12T00:00:00+00:00",
                  "birth_place": "Michoacán",
                  "weight": null,
                  "height": null,
                  "role": "Preparador físico",
                  "role_short": "PF",
                  "image": "https://venados.dacodes.mx/img/usr/30e2c9b5db20443e9d7057c5d1403a2f.jpg"
              },
              {
                  "name": "José Carlos",
                  "first_surname": "Narvaez",
                  "second_surname": "Borges",
                  "birthday": "1990-12-05T00:00:00+00:00",
                  "birth_place": "Mérida",
                  "weight": null,
                  "height": null,
                  "role": "Fisioterapeuta",
                  "role_short": "FIS",
                  "image": "https://venados.dacodes.mx/img/usr/6748ec0ba6fc42d1bdce6d54494735e1.jpg"
              },
              {
                  "name": "Alberto",
                  "first_surname": "Gutiérrez",
                  "second_surname": "Castañeda",
                  "birthday": "1980-12-13T00:00:00+00:00",
                  "birth_place": "León",
                  "weight": null,
                  "height": null,
                  "role": "Utilero",
                  "role_short": "UT",
                  "image": "https://venados.dacodes.mx/img/usr/563b172180844a57a8194a3c9f86bc69.jpg"
              },
              {
                  "name": "Santiago",
                  "first_surname": "Dorantes",
                  "second_surname": "Solís",
                  "birthday": "1982-08-16T00:00:00+00:00",
                  "birth_place": "Progreso",
                  "weight": null,
                  "height": null,
                  "role": "Médico",
                  "role_short": "MED",
                  "image": "https://venados.dacodes.mx/img/usr/0f9e2f7671c24270a4ef2b8777e2485d.jpg"
              },
              {
                  "name": "Alejandro",
                  "first_surname": "Cabrera",
                  "second_surname": "Lara",
                  "birthday": "1987-03-01T00:00:00+00:00",
                  "birth_place": "Mérida",
                  "weight": null,
                  "height": null,
                  "role": "Utilero",
                  "role_short": "UT",
                  "image": "https://venados.dacodes.mx/img/usr/f09e63359fab46e6a11afa5bee957f27.jpg"
              }
          ]
      },
      "code": 200
  }
}